apiVersion: apps/v1
kind: Deployment
metadata:
  name: codearena-backend
  namespace: codearena
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codearena-worker
  namespace: codearena
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
