apiVersion: v1
kind: Namespace
metadata:
  name: codearena
  labels:
    app.kubernetes.io/name: codearena
    app.kubernetes.io/part-of: codearena
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
