apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: codearena-backend-monitor
  namespace: codearena
  labels:
    app.kubernetes.io/name: codearena-backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: codearena-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
